name: 'Get Last Successful Deployment'
description: "Returns the last successful deployment for a given environment"
inputs:
  environment:
    description: "Environment to check"
outputs:
  deployment-sha:
    description: "Git sha for last successful deployment"
    value: ${{steps.get-last-successful-deployment.outputs.deployment-sha}}
  deployment:
    description: "Deployment JSON"
    value: ${{steps.get-last-successful-deployment.outputs.deployment}}
runs:
  using: "composite"
  steps:
  - uses: actions/github-script@v5
    id: get-last-successful-deployment
    with:
      script: |
        const result = await github.request('GET /repos/{owner}/{repo}/deployments', {
                                owner: context.repo.owner,
                                repo: context.repo.repo
                              })
        const deployments = response.data.filter(deployment => deployment.environment === 'production')
        const most_recent_deployment = deployments[0]
        core.debug(most_recent_deployment)
        var recent_successful_deployment = null;

        for (const deployment of deployments) {
          const response = await github.request(deployment.statuses_url)
          const deployment_statuses = response.data
          for(const deployment_status of deployment_statuses) {
            if( (deployment_status.state === 'success') && (deployment.id != most_recent_deployment.id) ) {
              recent_successful_deployment = deployment
              break
            }
          }
          if(recent_successful_deployment != null)
            break
        }
        core.debug(last_successful_deployment)
        core.setOutput('deployment', JSON.stringify(last_successful_deployment))
        core.setOutput('deployment-sha', last_successful_deployment.sha)
