name: Build Container Image
on:
  workflow_dispatch:
  workflow_call:
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install --silent

    - name: Build site
      run:  npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: build-image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha || github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - run: |
        echo ${{ steps.build-image-outputs.metadata }}
    