name: Cleanup PR
on:
  pull_request:
    types: [closed]
    branches: main

permissions:
  contents: read
  
jobs:
  delete-review-app:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-helm@v2.1
    - uses: azure/setup-kubectl@v1
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
    - run: |
        stable_release_name=${{ github.event.repository.name }}-pr-${{github.event.number}}
        kube_namespace=${{github.repository_owner }}-${{ github.event.repository.name }}-pr-${{ github.event.number }}

        helm uninstall "$stable_release_name" --namespace="$kube_namespace" --wait || true

