name: Deploy Site
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build
    uses: pied-piper-inc/popular-repos-web-app-kube/.github/workflows/build-image.yml@main

