name: Deploy Site
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  BASE_DOMAIN: piedpiper.patterson.io
  CHART: nano-byte/generic-service
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  build:
    name: Build
    uses: pied-piper-inc/popular-repos-web-app-kube/.github/workflows/build-image.yml@main
  code-analysis:
    uses: pied-piper-inc/popular-repos-web-app-kube/.github/workflows/codeql-analysis.yml@main
  deploy-review:
    needs: build
    if: github.event_name == 'pull_request'
    environment:
      name: review-lab
      url: ${{ steps.deploy-app.outputs.url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/auto-deploy-app
      with:
        app-domain: pr-${{ github.event.number }}-${{ env.BASE_DOMAIN }}
        image-tag: ${{ env.IMAGE_TAG }}
        kube-config: ${{ secrets.KUBE_CONFIG }}
        kube-namespace: ${{github.repository_owner }}-${{ github.event.repository.name }}-pr-${{ github.event.number }}
