name: Deploy Site
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  BASE_DOMAIN: piedpiper.patterson.io
  CHART: nano-byte/generic-service
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  build:
    uses: pied-piper-inc/workflows/.github/workflows/build-image.yml@main
  code-analysis:
    uses: pied-piper-inc/workflows/.github/workflows/code-analysis.yml@main
    with:
      languages: 'javascript'
  deploy-review:
    needs: [build]
    if: github.event_name == 'pull_request' && !contains(github.actor, 'dependabot')
    environment:
      name: review-lab
      url: ${{ steps.deploy-app.outputs.app-url }}
    concurrency: pr-${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
    - uses: pied-piper-inc/workflows/actions/auto-deploy@main
      id: deploy-app
      with:
        app-domain: pr-${{ github.event.number }}-${{ github.event.repository.name }}.${{ env.BASE_DOMAIN }}
        image-tag: ${{ env.IMAGE_TAG }}
        kube-config: ${{ secrets.KUBE_CONFIG }}
        kube-namespace: ${{github.repository_owner }}-${{ github.event.repository.name }}-pr-${{ github.event.number }}

  deploy-staging:
    needs: [build, code-analysis]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: 
      name: staging
      url: ${{ steps.deploy-app.outputs.app-url }}
    concurrency: staging
    steps:
    - uses: pied-piper-inc/workflows/actions/auto-deploy@main
      id: deploy-app
      with:
        app-domain: ${{ github.event.repository.name }}-staging.${{ env.BASE_DOMAIN }}
        image-tag: ${{ env.IMAGE_TAG }}
        kube-config: ${{ secrets.KUBE_CONFIG }}
        kube-namespace: ${{github.repository_owner }}-${{ github.event.repository.name }}-staging

  deploy-production:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-app.outputs.app-url }}
    concurrency: production
    steps:
    - uses: pied-piper-inc/workflows/actions/auto-deploy@main
      id: deploy-app
      with:
        app-domain: ${{ github.event.repository.name }}-production.${{ env.BASE_DOMAIN }}
        image-tag: ${{ env.IMAGE_TAG }}
        kube-config: ${{ secrets.KUBE_CONFIG }}
        kube-namespace: ${{github.repository_owner }}-${{ github.event.repository.name }}-production
