name: Get Logs For Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment you want to rollback'
        required: true
        default: 'production'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/get-last-successful-deployment
      id: last-successful-deployment
      with:
        environment: ${{ github.event.inputs.environment }}
    - uses: ./.github/actions/auto-deploy-app
      id: deploy-app
      env:
        IMAGE_TAG: ${{ steps.last-successful-deployment.outputs.deployment-sha }}
      with:
        app-domain: ${{ github.event.repository.name }}-${{ inputs.environment }}.${{ env.BASE_DOMAIN }}
        image-tag: ${{ env.IMAGE_TAG }}
        kube-config: ${{ secrets.KUBE_CONFIG }}
        kube-namespace: ${{github.repository_owner }}-${{ github.event.repository.name }}-${{ inputs.environment }}



        kubectl logs --selector app=pied-piper-inc-popular-repos-web-app-kube-production --namespace pied-piper-inc-popular-repos-web-app-kube-production