name: Get Logs For Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment you want to collect logs for'
        required: true
        default: 'production'

jobs:
  get-logs:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-kubectl@v1
    - uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
    - run: |
        if [[ -n "$GITHUB_HEAD_REF" ]]; then
          stable_release_name=${{ github.event.repository.name }}-pr-${{github.event.number}}
        else
          stable_release_name=${{github.repository_owner }}-${{ github.event.repository.name }}-${{ github.event.inputs.environment }}
        fi

        kubectl logs --selector app=$stable_release_name --namespace $stable_release_name