name: Rollback Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment you want to rollback'
        required: true
        default: 'production'
env:
  BASE_DOMAIN: piedpiper.patterson.io

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deploy-app.outputs.app-url }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/get-last-successful-deployment
      id: last-successful-deployment
      with:
        environment: ${{ github.event.inputs.environment }}
    - uses: pied-piper-inc/workflows/actions/auto-deploy@main
      id: deploy-app
      with:
        app-domain: ${{ github.event.repository.name }}-${{ github.event.inputs.environment }}.${{ env.BASE_DOMAIN }}
        image-tag: ${{ steps.last-successful-deployment.outputs.deployment-sha }}
        kube-config: ${{ secrets.KUBE_CONFIG }}
        kube-namespace: ${{github.repository_owner }}-${{ github.event.repository.name }}-${{ github.event.inputs.environment }}
